export const API_CONSTANTS = {
    API_SEVER             : 'https://sailor-erp.herokuapp.com',
    USER_LOGIN            : '/api/app/user/login',
    FORGOT_PASSWORD       : '/api/app/user/forgot/password',
    WEB_EDITOR            : '/api/app/editor',
    ADD_POST              : '/api/app/add/post',
    DELETE_POST           : '/api/app/delete/post',    
    GET_USER_DATA         : '/api/app/get/user/data',
    GET_USER_POSTS        : '/api/app/get/user/posts',
    GET_SCHOOL_POSTS      : '/api/app/get/shchool/posts',
    GET_SUBJECT_DATA      : '/api/app/get/subject/data',
    UPDATE_SUB_SYLLABUS   : '/api/app/update/subject/syllabus',
    GET_USER_TIMETABLE    : '/api/app/get/user/timetable',
    GET_USER_CLASSES      : '/api/app/get/user/classes',
    GET_USER_SYLLABUS     : '/api/app/get/user/syllabus',
    POST_CLASS_ATTENDENCE : '/api/app/post/class/attendence',
    GET_MY_CLASS          : '/api/app/get/my/class',
    UPDATE_USER_PROFILE   : '/api/app/update/user/profile',
    APPLY_FOR_LEAVE       : '/api/app/user/apply/leave',
    GET_USER_LEAVES       : '/api/app/user/leaves',
    DELETE_USER_LEAVE     : '/api/app/user/delete/leave',
    POST_CLASS_HOMEWORK   : '/api/app/post/homework',
    GET_USER_REPORTS      : '/api/app/user/reports',
    CREATE_EXAM           : '/api/app/create/exam',
    GET_USER_EXAMS        : '/api/app/get/exams',
    GET_CLASS_STUDENTS    : '/api/app/get/class/students',
    POST_EXAM_MARKS       : '/api/app/post/studennts/marks',
    POST_NOTIFICATION     : '/api/app/user/add/notifications',
    GET_MY_NOTIFICATIONS  : '/api/app/get/my/notifications',
    DELETE_NOTIFICATION   : '/api/app/delete/notification'       
}
 